
# Empirical analisys of complexity time using the package GuessCompx
```{r}
library(dplyr)
library(boot)
library(GuessCompx)
df=read.csv("dados.csv")

to.model = df %>% select(size=Input, time=ParDRe) %>% mutate(NlogN_X=size*log(size))
```

# creation of complexity models
```{r}
constant          <- glm(time~1,          data=to.model); to.model['constant'] = fitted(constant)
linear            <- glm(time~size,       data=to.model); to.model['linear'] = fitted(linear)
fractional_power  <- glm(time~I(size^1.5),  data=to.model); to.model['fractional power'] = fitted(fractional_power)
quadratic         <- glm(time~I(size^2),  data=to.model); to.model['quadratic'] = fitted(quadratic)
cubic             <- glm(time~I(size^3),  data=to.model); to.model['cubic'] = fitted(cubic)
quadruple         <- glm(time~I(size^4),  data=to.model); to.model['quadruple'] = fitted(quadruple)
log_factorial     <- glm(time~lfactorial(size), data=to.model); to.model['log factorial'] = fitted(log_factorial)
squareroot        <- glm(time~sqrt(size), data=to.model); to.model['squareroot'] = fitted(squareroot)
log_log           <- glm(time~log(log(size)),  data=to.model); to.model['log-logarithmic'] = fitted(log_log)
log               <- glm(time~log(size),  data=to.model); to.model['log'] = fitted(log)
NlogN             <- glm(time~NlogN_X,    data=to.model); to.model['NlogN'] = fitted(NlogN)
```

```{r}
model.list <- list('constant'   = constant,
                   'linear'     = linear,
                   'fractional power' = fractional_power,
                   'quadratic'  = quadratic,
                   'cubic'      = cubic,
                   'quadruple'  = quadruple,
                   'log factorial'  = log_factorial,
                   'squareroot' = squareroot,
                   'log-logarithmic' = log_log,
                   'log'        = log,
                   'NlogN'      = NlogN)
```

# Determining complexity to the best adjusted model
```{r}
benchmark   <- lapply(model.list, function(x) cv.glm(to.model, x)$delta[2])
best.model  <- names(which.min(benchmark))
print(best.model)
```





